### PR TITLE
Rip out capstone

### PR DESCRIPTION
**Pull request by HMPerson1**

### CODE REVIEW

**Comment by XVilka** [comment]
Can't we do both? Update capstone-rust in master and merge this one in "dev" branch?
Because if it will break some things - it might be bad for the first release.

**Comment by chinmaydd** [comment]
That sounds good to me :+1:

**Comment by kriw** [comment]
LGTM :)

**Comment by HMPerson1** [comment]
Merged to branch `dev`.

**Comment by radare** [comment]
😍

**Pull request closed without merging**
