### PR TITLE
Implement conditions

### PR DESCRIPTION
**Pull request by HMPerson1**
- [x] Associativity/Commutativity
- [x] Idempotence
- [x] Annihilation
- [x] De Morgan's
- [x] Distributivity
- [x] Absorption (`a AND (a OR b) ==> a`)
- [x] Complementation (`a AND -a ==> FALSE`)
- [x] Cover (I made up a name) (`a AND (-a OR b) ==> a AND b`)

### CODE REVIEW

**Comment by HMPerson1** [comment]
@sushant94 This is ready to be merged.

**Comment by XVilka** [comment]
@sushant94 @chinmaydd please review the PR.

**Comment by chinmaydd** [comment]
Sorry, totally forgot. I will do it by tonight.

**Comment by chinmaydd** [comment]
This is super neat work @HMPerson1 . LGTM!

**Comment by HMPerson1** [comment]
@chinmaydd Are you referring to the parts that I marked `// TODO: inefficient`? Those are places where we could have an index at which we can `Vec::swap_remove` in constant time, rather than linearly searching through the vec. The problem is that `LinearSet` doesn't support doing that; my plan for if that turned out to be a performance problem was just to reimplement `LinearSet` with support for that through something like the `HashMap`'s `Entry` API.

**Comment by sushant94** [comment]
I think @chinmaydd has reviewed this. Merging!

**Comment by chinmaydd** [comment]
@HMPerson1 I see. I was mostly interested in the `insert_one` function and seeing if we can find some more idioms we can simplify straight off-the-bat. I might be wrong, but I wanted to try it out.

**Pull request merged**
