### PR TITLE
Recover function call

### PR DESCRIPTION
**Pull request by kriw**
Related to #156 

- [x] Recover function name
- [x] Recover function arguments
- [x] Sort the arguments by calling convention
- [x] Add return value
- [x] Fix broken debug output

### CODE REVIEW

**Comment by kriw** [comment]
This PR is ready to be merged.

**Comment by XVilka** [comment]
@sushant94 @chinmaydd please review the PR.

**Comment by chinmaydd** [comment]
Yep, this looks good to me. @kriw I would like you to make sure that `CASTBuilder::new` does not incrementally take more arguments as we try to improve our analyses. Maybe you can abstract all that information into a single struct. 😄

**Comment by XVilka** [comment]
@kriw can you please also add tests for this feature?

**Comment by kriw** [comment]
@chinmaydd  Thank you for reviewing.
>  @kriw I would like you to make sure that CASTBuilder::new does not incrementally take more arguments as we try to improve our analyses


I think I will add one more argument (symbol table) in the future. Could you tell me why `CASTBuilder` is related to improving our analyses?

> Maybe you can abstract all that information into a single struct.

Did you mean it is better to make `CASTBuilder` and `CASTDataMap`? If so, I think it would be simpler to separate them because `CASTDataMap` is a kind of use-def chain and `CASTBuilder` is for recovering actions with immutable `CASTDataMAP`.

**Pull request merged**
