### PR TITLE
Recover local variables

### PR DESCRIPTION
**Pull request by kriw**
Related to #156

### CODE REVIEW

**Comment by XVilka** [comment]
Are there any updates lately on this?

**Comment by XVilka** [comment]
@chinmaydd @sushant94 please review

**Comment by sushant94** [comment]
@XVilka I've seen this. Its still WIP, so I didn't comment on anything.

**Comment by kriw** [comment]
The remain task is adding a kind of debug information to the output.

**Comment by kriw** [comment]
This is ready to be merged.

Currently, `inst_combine` modify SSA node(e.g., `rbp - 0x10` to `rsp - 0x8`), so it fails to recover local variables correctly. The information of locals are holded by `RadecoFunction::binding_map: HashMap<NodeIndex, VarBinding>`, so if analyses modify SSA nodes, we have to fix `binding_map` for recover locals correctly. This problem is related to the issue #172, because the problems might be occurred by every analysis which modify SSA.

**Comment by sushant94** [comment]
SGTM, I'd like a way to do the binding fix automatically, or have the recover bindings run very late in the analysis stage. This is something that needs to be discussed, please open an issue for the same.

Merging. Thanks!

**Pull request merged**
